# Generated by Django 4.0.4 on 2022-06-11 12:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='b_context',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
